#ifndef MISTAKES_H
#define MISTAKES_H
#include <stdint.h>

typedef uint64_t TreeErr_t;

enum Err{
    NO_MISTAKE,
    NULL_NODE_PTR,
    INCORRECT_SIGN,
    INCORR_CONNECT_PARENT_CHILD,
    INCORR_LEFT_CONNECT,
    INCORR_RIGHT_CONNECT,
    LOOPED_NODE,
    INCORR_OUTPUT_FILE,
    CANT_OPEN_OUT_FILE,
    CANT_FIND_NODE,
    CANT_FIND_PATH,
    ALLOC_ERR,
    INCORR_VAR_TO_DIFF,
    INCORR_FILE,
    INCORR_OPERATOR,
    INCORR_TYPE,
    NO_ELEM_FOR_BINARY_OP,
    NULL_PTR_TO_FUNC,
    CANT_GET_VALUE_FOR_NULL_NAME_IN_MTK,
    NULL_PTR_TO_MTK,
    INCORR_IDX_IN_MTK,
    NULL_RES_PTR,
    NULL_IS_OPT_PTR,
    NOT_ALL_INFO_IN_MTK,
    NULL_FOREST_PTR,
    NULL_MTK_PTR,
    INCORR_USER_INPUT_VALUE,
    CANT_CREATE_FILE_FOR_GP_DUMP,
    CANT_MAKE_GRAPH,
};

#endif //MISTAKES_H